name: zs_bluetooth_printer
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^3.1.0
  shared_preferences: ^0.5.12+2
  fish_redux: ^0.3.4
  flutter_blue:
    git:
      url: https://github.com/xiyuxiaoxiao/flutter_public.git
      path: flutter_blue-0.7.3
      #ref: '1.0.3'

  zs_flutter_data:
    git:
      url: https://github.com/xiyuxiaoxiao/flutter_public.git
      path: zs_flutter_data

  zs_permisson:
    git:
      url: https://github.com/xiyuxiaoxiao/flutter_public.git
      path: zs_permisson

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
